# Generated by Django 5.0.3 on 2024-03-14 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=20)),
                ("creation_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("creation_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-creation_date"],
            },
        ),
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("save_date", models.DateField(auto_now_add=True)),
                (
                    "type",
                    models.IntegerField(
                        choices=[
                            ("article", "Article"),
                            ("video", "Video"),
                            ("image", "Image"),
                            ("audio", "Audio"),
                        ],
                        default="article",
                    ),
                ),
                ("note", models.TextField(blank=True, null=True)),
                ("has_been_read", models.BooleanField(blank=True, default=False)),
                ("is_starred", models.BooleanField(blank=True, default=False)),
                (
                    "tag",
                    models.ManyToManyField(
                        blank=True, related_name="tagged_links", to="store.tag"
                    ),
                ),
                (
                    "topic",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="topic_links",
                        to="store.topic",
                    ),
                ),
            ],
            options={
                "ordering": ["-save_date", "has_been_read"],
            },
        ),
    ]
