# Generated by Django 5.0.3 on 2024-03-21 04:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_link_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="type",
            field=models.CharField(
                choices=[
                    ("article", "Article"),
                    ("video", "Video"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                ],
                default="article",
                max_length=10,
            ),
        ),
    ]
