# Generated by Django 5.0.3 on 2024-03-21 12:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_link_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="url",
            field=models.URLField(max_length=600),
        ),
    ]
