# Generated by Django 5.0.3 on 2024-06-10 00:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0004_alter_link_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="link",
            name="read_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="link",
            name="type",
            field=models.CharField(
                choices=[
                    ("article", "Article"),
                    ("video", "Video"),
                    ("image", "Image"),
                    ("audio", "Audio"),
                    ("document", "Document"),
                ],
                default="article",
                max_length=10,
            ),
        ),
    ]
