# Generated by Django 5.0.6 on 2024-07-22 01:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0006_tag_owner_topic_owner"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="link",
            options={"ordering": ["-saved_on", "has_been_read"]},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"ordering": ["-updated_on"]},
        ),
        migrations.AlterModelOptions(
            name="topic",
            options={"ordering": ["-updated_on"]},
        ),
        migrations.RenameField(
            model_name="link",
            old_name="save_date",
            new_name="saved_on",
        ),
        migrations.RenameField(
            model_name="tag",
            old_name="creation_date",
            new_name="created_on",
        ),
        migrations.RenameField(
            model_name="topic",
            old_name="creation_date",
            new_name="created_on",
        ),
        migrations.AddField(
            model_name="link",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="tag",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name="topic",
            name="updated_on",
            field=models.DateField(auto_now=True),
        ),
    ]
