# Generated by Django 5.0.6 on 2024-07-22 14:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0007_alter_link_options_alter_tag_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="title",
            field=models.CharField(max_length=600),
        ),
    ]
