# Generated by Django 5.0.6 on 2024-07-26 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_alter_link_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="link",
            name="topic",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="topic_links",
                to="store.topic",
            ),
        ),
    ]
